# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/helper-validator-identifier-7.16.7" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.16.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.16.7.tgz";
        sha512 = "hsEnFemeiW4D08A5gUAZxLBTXpZ39P+a+DGDsHw1yxqyQ/jzFEnxf5uTEGp+3bzAbNOxU1paTgYS4ECU/IgfDw==";
      };
    };
    "@babel/parser-7.18.4" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.18.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.18.4.tgz";
        sha512 = "FDge0dFazETFcxGw/EXzOkN8uJp0PC7Qbm+Pe9T+av2zlBpOgunFHkQPPn+eRuClU73JF+98D531UgayY89tow==";
      };
    };
    "@babel/types-7.18.4" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.18.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.18.4.tgz";
        sha512 = "ThN1mBcMq5pG/Vm2IcBmPPfyPXbd8S02rS+OBIDENdufvqC7Z/jHPCv9IcP01277aKtDI8g/2XysBN4hA8niiw==";
      };
    };
    "@emmetio/abbreviation-2.2.3" = {
      name = "_at_emmetio_slash_abbreviation";
      packageName = "@emmetio/abbreviation";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.2.3.tgz";
        sha512 = "87pltuCPt99aL+y9xS6GPZ+Wmmyhll2WXH73gG/xpGcQ84DRnptBsI2r0BeIQ0EB/SQTOe2ANPqFqj3Rj5FOGA==";
      };
    };
    "@emmetio/css-abbreviation-2.1.4" = {
      name = "_at_emmetio_slash_css-abbreviation";
      packageName = "@emmetio/css-abbreviation";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.4.tgz";
        sha512 = "qk9L60Y+uRtM5CPbB0y+QNl/1XKE09mSO+AhhSauIfr2YOx/ta3NJw2d8RtCFxgzHeRqFRr8jgyzThbu+MZ4Uw==";
      };
    };
    "@emmetio/scanner-1.0.0" = {
      name = "_at_emmetio_slash_scanner";
      packageName = "@emmetio/scanner";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.0.tgz";
        sha512 = "8HqW8EVqjnCmWXVpqAOZf+EGESdkR27odcMMMGefgKXtar00SoYNSryGv//TELI4T3QFsECo78p+0lmalk/CFA==";
      };
    };
    "@johnsoncodehk/html2pug-1.0.0" = {
      name = "_at_johnsoncodehk_slash_html2pug";
      packageName = "@johnsoncodehk/html2pug";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@johnsoncodehk/html2pug/-/html2pug-1.0.0.tgz";
        sha512 = "TAs9NvSxC2ceT11h9Hck/p4No3lyaAtYUfV0ttPgImLxfbrAtvID5pdQVC5j1hYa/0oMg+Q4Xq91yihSgeAmgQ==";
      };
    };
    "@johnsoncodehk/pug-beautify-0.2.2" = {
      name = "_at_johnsoncodehk_slash_pug-beautify";
      packageName = "@johnsoncodehk/pug-beautify";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@johnsoncodehk/pug-beautify/-/pug-beautify-0.2.2.tgz";
        sha512 = "qqNS/YD0Nck5wtQLCPHAfGVgWbbGafxSPjNh0ekYPFSNNqnDH2kamnduzYly8IiADmeVx/MfAE1njMEjVeHTMA==";
      };
    };
    "@types/commander-2.12.2" = {
      name = "_at_types_slash_commander";
      packageName = "@types/commander";
      version = "2.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/commander/-/commander-2.12.2.tgz";
        sha512 = "0QEFiR8ljcHp9bAbWxecjVRuAMr16ivPiGOw6KFQBVrVd0RQIcM3xKdRisH2EDWgVWujiYtHwhSkSUoAAGzH7Q==";
      };
    };
    "@types/diff-3.5.5" = {
      name = "_at_types_slash_diff";
      packageName = "@types/diff";
      version = "3.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/diff/-/diff-3.5.5.tgz";
        sha512 = "aqcrAbqT/0+ULJJ73bwKWsiFkBh3ZnAelj9u+iI5/cr4Nz3yXGf3w4glx5am6uvvgBbKinK1PAqSJs7fSKD6ig==";
      };
    };
    "@types/get-stdin-5.0.1" = {
      name = "_at_types_slash_get-stdin";
      packageName = "@types/get-stdin";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/get-stdin/-/get-stdin-5.0.1.tgz";
        sha512 = "hkShVHsKPKK4OulBjeYi15m5RQRR2ZV7ItFEa3C+QEay81MenD5ZfcTxzlo3ZaUTkbCbpw5XIW/NWKQNWq+Q/A==";
      };
    };
    "@types/node-17.0.36" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.36.tgz";
        sha512 = "V3orv+ggDsWVHP99K3JlwtH20R7J4IhI1Kksgc+64q5VxgfRkQG8Ws3MFm/FZOKDYGy9feGFlZ70/HpCNe9QaA==";
      };
    };
    "@volar/code-gen-0.35.2" = {
      name = "_at_volar_slash_code-gen";
      packageName = "@volar/code-gen";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/code-gen/-/code-gen-0.35.2.tgz";
        sha512 = "MoZHuNnPfUWnCNkQUI5+U+gvLTxrU+XlCTusdNOTFYUUAa+M68MH0RxFIS9Ybj4uAUWTcZx0Ow1q5t/PZozo+Q==";
      };
    };
    "@volar/pug-language-service-0.35.2" = {
      name = "_at_volar_slash_pug-language-service";
      packageName = "@volar/pug-language-service";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/pug-language-service/-/pug-language-service-0.35.2.tgz";
        sha512 = "eTPlPlDtvWug93WWZeP+K/tt5YUQlBSst7qvnn6m/RN4292h8ht86H28IkcdD2hmzoqDYi/HJSUrypmeh0vBnw==";
      };
    };
    "@volar/shared-0.35.2" = {
      name = "_at_volar_slash_shared";
      packageName = "@volar/shared";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/shared/-/shared-0.35.2.tgz";
        sha512 = "PHgb2inrw7PMdZg3uzXw1zaMOpvDoF0g3E1LPVD+S8tq978lAj5eM1jqhKQdHd6lI60q1btwGXAfB+yTyH9QMQ==";
      };
    };
    "@volar/source-map-0.35.2" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-0.35.2.tgz";
        sha512 = "PFHh9wN/qMkOWYyvmB8ckvIzolrpNOvK5EBdxxdTpiPJhfYjW82rMDBnYf6RxCe7yQxrUrmve6BWVO7flxWNVQ==";
      };
    };
    "@volar/transforms-0.35.2" = {
      name = "_at_volar_slash_transforms";
      packageName = "@volar/transforms";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/transforms/-/transforms-0.35.2.tgz";
        sha512 = "pVfhx1gEHgmkSv16ihpd0sfhUlt81IVC8ZzCVn5tmtIbSriT9n71eO4lfhVrHPv4mr0i2VX92j9VOSYP5wLppA==";
      };
    };
    "@volar/typescript-language-service-0.35.2" = {
      name = "_at_volar_slash_typescript-language-service";
      packageName = "@volar/typescript-language-service";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript-language-service/-/typescript-language-service-0.35.2.tgz";
        sha512 = "/HebTbWEaTiVzztw7TksKK/NOVkthKSffsU+tHZaHne1kSC4qyAhXbdkchqo0Z0rAYOr+bzR7LM1Rt3xpkIcaw==";
      };
    };
    "@volar/vue-code-gen-0.35.2" = {
      name = "_at_volar_slash_vue-code-gen";
      packageName = "@volar/vue-code-gen";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-code-gen/-/vue-code-gen-0.35.2.tgz";
        sha512 = "8H6P8EtN06eSVGjtcJhGqZzFIg6/nWoHVOlnhc5vKqC7tXwpqPbyMQae0tO7pLBd5qSb/dYU5GQcBAHsi2jgyA==";
      };
    };
    "@volar/vue-language-service-0.35.2" = {
      name = "_at_volar_slash_vue-language-service";
      packageName = "@volar/vue-language-service";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-language-service/-/vue-language-service-0.35.2.tgz";
        sha512 = "QnAshBCR8V3TAf2rIyAL7o7LZv/eLSgGlKWdZIIcnk5+B5FNgNZI0wiH4tq+4pZiU5cpxh+DYM3d2UEnSvT2SA==";
      };
    };
    "@volar/vue-language-service-types-0.35.2" = {
      name = "_at_volar_slash_vue-language-service-types";
      packageName = "@volar/vue-language-service-types";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-language-service-types/-/vue-language-service-types-0.35.2.tgz";
        sha512 = "xA1g8SMIxNsWpurn7vT51OCyO+BGQhjLcj346zgu4H16jb7jRbXqybzjs191K1KLqT6T/92ZCjKBs5MBDy/3kQ==";
      };
    };
    "@volar/vue-typescript-0.35.2" = {
      name = "_at_volar_slash_vue-typescript";
      packageName = "@volar/vue-typescript";
      version = "0.35.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/vue-typescript/-/vue-typescript-0.35.2.tgz";
        sha512 = "PZI6Urb+Vr5Dvgf9xysM8X7TP09inWDy1wjDtprBoBhxS7r0Dg3V0qZuJa7sSGz7M0QMa5R/CBaZPhlxFCfJBw==";
      };
    };
    "@vscode/emmet-helper-2.8.4" = {
      name = "_at_vscode_slash_emmet-helper";
      packageName = "@vscode/emmet-helper";
      version = "2.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.8.4.tgz";
        sha512 = "lUki5QLS47bz/U8IlG9VQ+1lfxMtxMZENmU5nu4Z71eOD5j9FK0SmYGL5NiVJg9WBWeAU0VxRADMY2Qpq7BfVg==";
      };
    };
    "@vue/compiler-core-3.2.36" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.2.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.2.36.tgz";
        sha512 = "bbyZM5hvBicv0PW3KUfVi+x3ylHnfKG7DOn5wM+f2OztTzTjLEyBb/5yrarIYpmnGitVGbjZqDbODyW4iK8hqw==";
      };
    };
    "@vue/compiler-dom-3.2.36" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.2.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.2.36.tgz";
        sha512 = "tcOTAOiW4s24QLnq+ON6J+GRONXJ+A/mqKCORi0LSlIh8XQlNnlm24y8xIL8la+ZDgkdbjarQ9ZqYSvEja6gVA==";
      };
    };
    "@vue/compiler-sfc-3.2.36" = {
      name = "_at_vue_slash_compiler-sfc";
      packageName = "@vue/compiler-sfc";
      version = "3.2.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-sfc/-/compiler-sfc-3.2.36.tgz";
        sha512 = "AvGb4bTj4W8uQ4BqaSxo7UwTEqX5utdRSMyHy58OragWlt8nEACQ9mIeQh3K4di4/SX+41+pJrLIY01lHAOFOA==";
      };
    };
    "@vue/compiler-ssr-3.2.36" = {
      name = "_at_vue_slash_compiler-ssr";
      packageName = "@vue/compiler-ssr";
      version = "3.2.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-ssr/-/compiler-ssr-3.2.36.tgz";
        sha512 = "+KugInUFRvOxEdLkZwE+W43BqHyhBh0jpYXhmqw1xGq2dmE6J9eZ8UUSOKNhdHtQ/iNLWWeK/wPZkVLUf3YGaw==";
      };
    };
    "@vue/reactivity-3.2.36" = {
      name = "_at_vue_slash_reactivity";
      packageName = "@vue/reactivity";
      version = "3.2.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity/-/reactivity-3.2.36.tgz";
        sha512 = "c2qvopo0crh9A4GXi2/2kfGYMxsJW4tVILrqRPydVGZHhq0fnzy6qmclWOhBFckEhmyxmpHpdJtIRYGeKcuhnA==";
      };
    };
    "@vue/reactivity-transform-3.2.36" = {
      name = "_at_vue_slash_reactivity-transform";
      packageName = "@vue/reactivity-transform";
      version = "3.2.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity-transform/-/reactivity-transform-3.2.36.tgz";
        sha512 = "Jk5o2BhpODC9XTA7o4EL8hSJ4JyrFWErLtClG3NH8wDS7ri9jBDWxI7/549T7JY9uilKsaNM+4pJASLj5dtRwA==";
      };
    };
    "@vue/shared-3.2.36" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.2.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.2.36.tgz";
        sha512 = "JtB41wXl7Au3+Nl3gD16Cfpj7k/6aCroZ6BbOiCMFCMvrOpkg/qQUXTso2XowaNqBbnkuGHurLAqkLBxNGc1hQ==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "adverb-where-0.2.5" = {
      name = "adverb-where";
      packageName = "adverb-where";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/adverb-where/-/adverb-where-0.2.5.tgz";
        sha512 = "JiQe2U1UR8l10jPrXv/PmlDhOLZpsxqjvTp+k6Dm5wYDUULdMZytDRmovkXU8X6V9o0sg0FBdetv3VXHAZZK5Q==";
      };
    };
    "agent-base-5.1.1" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-5.1.1.tgz";
        sha512 = "TMeqbNl2fMW0nMjTEPOwe3J/PRFP4vqeoNuQMG0HlMrtm5QxKqdvAkZ1pRBQ/ulIyDD5Yq0nJ7YbdD8ey0TO3g==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha512 = "BSHWgDSAiKs50o2Re8ppvp3seVHXSRM44cdSsT9FfNEUUZLOGWVCsiWaRPWM1Znn+mqZ1OfVZ3z3DWEzSp7hRA==";
      };
    };
    "assert-never-1.2.1" = {
      name = "assert-never";
      packageName = "assert-never";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-never/-/assert-never-1.2.1.tgz";
        sha512 = "TaTivMB6pYI1kXwrFlEhLeGfOqoDNdTxjCdwRfFFkEA30Eu+k48W34nlok2EYWJfFFzqaEmichdNM7th6M5HNw==";
      };
    };
    "babel-walk-3.0.0-canary-5" = {
      name = "babel-walk";
      packageName = "babel-walk";
      version = "3.0.0-canary-5";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-walk/-/babel-walk-3.0.0-canary-5.tgz";
        sha512 = "GAwkz0AihzY5bkwIY5QDR+LvsRQgB/B+1foMPvi0FZPMl5fjD7ICiznUiBdLYMH1QYe6vqu4gWYytZOccLouFw==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "constantinople-4.0.1" = {
      name = "constantinople";
      packageName = "constantinople";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/constantinople/-/constantinople-4.0.1.tgz";
        sha512 = "vCrqcSIq4//Gx74TXXCGnHpulY1dskqLTFGDmhrGxzeXL8lF8kvXv6mpNWlJj1uD4DW23D4ljAqbY4RRaaUZIw==";
      };
    };
    "core_d-5.0.1" = {
      name = "core_d";
      packageName = "core_d";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core_d/-/core_d-5.0.1.tgz";
        sha512 = "37lZyhJY1hzgFbfU4LzY4zL09QPwPfV2W/3YBOtN7mkdvVaeP1OVnDZI6zxggtlPwG/BuE5wIr0xptlVJk5EPA==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "diff-3.5.0" = {
      name = "diff";
      packageName = "diff";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-3.5.0.tgz";
        sha512 = "A46qtFgd+g7pDZinpnwiRJtxbC1hpgf0uzP3iG89scHk0AUC7A1TGxf5OiiOUv/JMZR8GOt8hL900hV0bOy5xA==";
      };
    };
    "doctypes-1.1.0" = {
      name = "doctypes";
      packageName = "doctypes";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctypes/-/doctypes-1.1.0.tgz";
        sha512 = "LLBi6pEqS6Do3EKQ3J0NqHWV5hhb78Pi8vvESYwyOy2c31ZEZVdtitdzsQsKb7878PEERhzUk0ftqGhG6Mz+pQ==";
      };
    };
    "dom-serializer-1.4.1" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-1.4.1.tgz";
        sha512 = "VHwB3KfrcOOkelEG2ZOfxqLZdfkil8PtJi4P8N2MMXucZq2yLp75ClViUlOVwyoHEDjYU433Aq+5zWP61+RGag==";
      };
    };
    "domelementtype-2.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
        sha512 = "OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
      };
    };
    "domhandler-4.3.1" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-4.3.1.tgz";
        sha512 = "GrwoxYN+uWlzO8uhUXRl0P+kHE4GtVPfYzVLcUxPL7KNdHKj66vvlhiweIHqYYXWlw+T8iLMp42Lm67ghw4WMQ==";
      };
    };
    "domutils-2.8.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.8.0.tgz";
        sha512 = "w96Cjofp72M5IIhpjgobBimYEfoPjx1Vx0BSX9P30WBdZW2WIKU0T1Bd0kz2eNZ9ikjKgHbEyKx8BB6H1L3h3A==";
      };
    };
    "e-prime-0.10.4" = {
      name = "e-prime";
      packageName = "e-prime";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/e-prime/-/e-prime-0.10.4.tgz";
        sha512 = "tzBmM2mFSnAq5BuxPSyin6qXb3yMe1wufJN7L7ZPcEWS5S+jI2dhKQEoqHVEcSMMXo/j5lcWpX5jzA6wLSmX6w==";
      };
    };
    "emmet-2.3.6" = {
      name = "emmet";
      packageName = "emmet";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/emmet/-/emmet-2.3.6.tgz";
        sha512 = "pLS4PBPDdxuUAmw7Me7+TcHbykTsBKN/S9XJbUOMFQrNv9MoshzyMFK/R57JBm94/6HSL4vHnDeEmxlC82NQ4A==";
      };
    };
    "entities-2.1.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.1.0.tgz";
        sha512 = "hCx1oky9PFrJ611mf0ifBLBRW8lUUVRlFolb5gWRfIELabBlbp9xZvrqZLZAs+NxFnbfQoeGd8wDkygjg7U85w==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "entities-3.0.1" = {
      name = "entities";
      packageName = "entities";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-3.0.1.tgz";
        sha512 = "WiyBqoomrwMdFG1e0kqvASYfnlb0lp8M5o5Fw2OFq1hNZxxcNk8Ik0Xm7LxzBhuidnZB/UtBqVCgUz3kBOP51Q==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-intrinsic-1.1.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.1.1.tgz";
        sha512 = "kWZrnVM42QCiEA2Ig1bG8zjoIMOgxWwYCEeNdwY6Tv/cOSeGpcoX4pXHfKUxNKVoArnrEr2e9srnAxxGIraS9Q==";
      };
    };
    "get-stdin-5.0.1" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-5.0.1.tgz";
        sha512 = "jZV7n6jGE3Gt7fgSTJoz91Ak5MuTLwMwkoYdjxuJ/AmjIsE1UC03y/IWkZCQGEvVNS9qoRNwy5BCqxImv0FVeA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "htmlparser2-7.2.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-7.2.0.tgz";
        sha512 = "H7MImA4MS6cw7nbyURtLPO1Tms7C5H602LRETv95z1MxO/7CP7rDVROehUYeYBUYEON94NXXDEPmZuq+hX4sog==";
      };
    };
    "https-proxy-agent-4.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-4.0.0.tgz";
        sha512 = "zoDhWrkR3of1l9QAL8/scJZyLu8j/gBkcwcaQOZh7Gyh/+uJQzGVETdgT30akuwkpL8HTRfssqI3BZuV18teDg==";
      };
    };
    "is-core-module-2.9.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.9.0.tgz";
        sha512 = "+5FPy5PnwmO3lvfMb0AsoPaBG+5KHUI0wYFXOtYPnVVVspTFUuMZNfNaNVRt3FZadstu2c8x23vykRW/NBoU6A==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-promise-2.2.2" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.2.2.tgz";
        sha512 = "+lP4/6lKUBfQjZ2pdxThZvLUAafmZb8OAxFb8XXtiQmS35INgr85hdOGoEs124ez1FCnZJt6jau/T+alh58QFQ==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "js-stringify-1.0.2" = {
      name = "js-stringify";
      packageName = "js-stringify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-stringify/-/js-stringify-1.0.2.tgz";
        sha512 = "rtS5ATOo2Q5k1G+DADISilDA6lv79zIiwFd6CcjuIxGKLFm5C+RLImRscVap9k55i+MOZwgliw+NejvkLuGD5g==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "jsonc-parser-3.0.0" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.0.0.tgz";
        sha512 = "fQzRfAbIBnR0IQvftw9FJveWiHp72Fg20giDrHz6TdfB12UH/uue0D3hm57UB5KgAVuniLMCaS8P1IMj9NR7cA==";
      };
    };
    "jstransformer-1.0.0" = {
      name = "jstransformer";
      packageName = "jstransformer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransformer/-/jstransformer-1.0.0.tgz";
        sha512 = "C9YK3Rf8q6VAPDCCU9fnqo3mAfOH6vUGnMcP4AQAYIEpWtfGLpwOTmZ+igtdK5y+VvI2n3CyYSzy4Qh34eq24A==";
      };
    };
    "linkify-it-3.0.3" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-3.0.3.tgz";
        sha512 = "ynTsyrFSdE5oZ/O9GEf00kPngmOfVwazR5GKDq6EYfhlpFug3J2zybX56a2PRRpc9P+FuSoGNAwjlbDs9jJBPQ==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "luaparse-git+https://github.com/oxyc/luaparse#ac42a00ebf4020b8c9d3219e4b0f84bf7ce6e802" = {
      name = "luaparse";
      packageName = "luaparse";
      version = "0.2.1";
      src = fetchgit {
        url = "https://github.com/oxyc/luaparse";
        rev = "ac42a00ebf4020b8c9d3219e4b0f84bf7ce6e802";
        sha256 = "f813d671f8f8088d70d29f7a7770bdd5ed41ed97240ae9346d7ced0c094ee049";
      };
    };
    "magic-string-0.25.9" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.25.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.25.9.tgz";
        sha512 = "RmF0AsMzgt25qzqqLc1+MbHmhdx0ojF2Fvs4XnOqz2ZOBXzzkEwc/dJQZCYHAn7v1jbVOjAZfK8msRn4BxO4VQ==";
      };
    };
    "markdown-it-12.3.2" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "12.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-12.3.2.tgz";
        sha512 = "TchMembfxfNVpHkbtriWltGWc+m3xszaRD0CZup7GFFhzIgQqxIfn3eGj1yZpfuflzPvfkt611B2Q/Bsk1YnGg==";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha512 = "/sKlQJCBYVY9Ers9hqzKou4H6V5UWc/M59TH2dvkt+84itfnq7uFOMLpOiOS4ujvHP4etln18fmIxA5R5fll0g==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nanoid-3.3.4" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.4.tgz";
        sha512 = "MqBkQh/OHTS2egovRtLk45wEyNXwF+cokD+1YPf9u5VfJiRdAiRwB2froX5Co9Rh20xs4siNPm8naNotSD6RBw==";
      };
    };
    "nanolru-1.0.0" = {
      name = "nanolru";
      packageName = "nanolru";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanolru/-/nanolru-1.0.0.tgz";
        sha512 = "GyQkE8M32pULhQk7Sko5raoIbPalAk90ICG+An4fq6fCsFHsP6fB2K46WGXVdoJpy4SGMnZ/EKbo123fZJomWg==";
      };
    };
    "no-cliches-0.3.4" = {
      name = "no-cliches";
      packageName = "no-cliches";
      version = "0.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-cliches/-/no-cliches-0.3.4.tgz";
        sha512 = "oUqnng1vhKLaA4GR+OzVbLuZZ7OOguKCtMHxHMiyP8+9mXidKfoCyc030LbAyNI3xcgCHHyitK3Q8wP+w6DwVQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "passive-voice-0.1.0" = {
      name = "passive-voice";
      packageName = "passive-voice";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/passive-voice/-/passive-voice-0.1.0.tgz";
        sha1 = "16ff91ae40ba0e92c43e671763fdc842a70270b1";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "postcss-8.4.14" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.14.tgz";
        sha512 = "E398TUmfAYFPBSdzgeieK2Y1+1cpdxJx8yXbK/m57nRhKSmk1GB2tO4lbLBtlkfPQTDKfe4Xqv1ASWPpayPEig==";
      };
    };
    "prettier-2.6.2" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.6.2.tgz";
        sha512 = "PkUpF+qoXTqhOeWL9fu7As8LXsIUZ1WYaJiY/a7McAQzxjk82OF0tibkFXVCDImZtWxbvojFjerkiLb0/q8mew==";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "nolQXZ/4L+bP/UGlkfaIujX9BKxGwmQ9OT4mOt5yvy8iK1h3wqTEJCijzGANTCCl9nWjY41juyAn2K3Q1hLLTg==";
      };
    };
    "proxy-from-env-1.1.0" = {
      name = "proxy-from-env";
      packageName = "proxy-from-env";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz";
        sha512 = "D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg==";
      };
    };
    "pug-3.0.2" = {
      name = "pug";
      packageName = "pug";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug/-/pug-3.0.2.tgz";
        sha512 = "bp0I/hiK1D1vChHh6EfDxtndHji55XP/ZJKwsRqrz6lRia6ZC2OZbdAymlxdVFwd1L70ebrVJw4/eZ79skrIaw==";
      };
    };
    "pug-attrs-3.0.0" = {
      name = "pug-attrs";
      packageName = "pug-attrs";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-attrs/-/pug-attrs-3.0.0.tgz";
        sha512 = "azINV9dUtzPMFQktvTXciNAfAuVh/L/JCl0vtPCwvOA21uZrC08K/UnmrL+SXGEVc1FwzjW62+xw5S/uaLj6cA==";
      };
    };
    "pug-code-gen-3.0.2" = {
      name = "pug-code-gen";
      packageName = "pug-code-gen";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-code-gen/-/pug-code-gen-3.0.2.tgz";
        sha512 = "nJMhW16MbiGRiyR4miDTQMRWDgKplnHyeLvioEJYbk1RsPI3FuA3saEP8uwnTb2nTJEKBU90NFVWJBk4OU5qyg==";
      };
    };
    "pug-error-2.0.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.0.0.tgz";
        sha512 = "sjiUsi9M4RAGHktC1drQfCr5C5eriu24Lfbt4s+7SykztEOwVZtbFk1RRq0tzLxcMxMYTBR+zMQaG07J/btayQ==";
      };
    };
    "pug-filters-4.0.0" = {
      name = "pug-filters";
      packageName = "pug-filters";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-filters/-/pug-filters-4.0.0.tgz";
        sha512 = "yeNFtq5Yxmfz0f9z2rMXGw/8/4i1cCFecw/Q7+D0V2DdtII5UvqE12VaZ2AY7ri6o5RNXiweGH79OCq+2RQU4A==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "pug-linker-4.0.0" = {
      name = "pug-linker";
      packageName = "pug-linker";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-linker/-/pug-linker-4.0.0.tgz";
        sha512 = "gjD1yzp0yxbQqnzBAdlhbgoJL5qIFJw78juN1NpTLt/mfPJ5VgC4BvkoD3G23qKzJtIIXBbcCt6FioLSFLOHdw==";
      };
    };
    "pug-load-3.0.0" = {
      name = "pug-load";
      packageName = "pug-load";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-load/-/pug-load-3.0.0.tgz";
        sha512 = "OCjTEnhLWZBvS4zni/WUMjH2YSUosnsmjGBB1An7CsKQarYSWQ0GCVyd4eQPMFJqZ8w9xgs01QdiZXKVjk92EQ==";
      };
    };
    "pug-parser-6.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz";
        sha512 = "ukiYM/9cH6Cml+AOl5kETtM9NR3WulyVP2y4HOU45DyMim1IeP/OOiyEWRr6qk5I5klpsBnbuHpwKmTx6WURnw==";
      };
    };
    "pug-runtime-3.0.1" = {
      name = "pug-runtime";
      packageName = "pug-runtime";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-runtime/-/pug-runtime-3.0.1.tgz";
        sha512 = "L50zbvrQ35TkpHwv0G6aLSuueDRwc/97XdY8kL3tOT0FmhgG7UypU3VztfV/LATAvmUfYi4wNxSajhSAeNN+Kg==";
      };
    };
    "pug-strip-comments-2.0.0" = {
      name = "pug-strip-comments";
      packageName = "pug-strip-comments";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-strip-comments/-/pug-strip-comments-2.0.0.tgz";
        sha512 = "zo8DsDpH7eTkPHCXFeAk1xZXJbyoTfdPlNR0bK7rpOMuhBYb0f5qUVCO1xlsitYd3w5FQTK7zpNVKb3rZoUrrQ==";
      };
    };
    "pug-walk-2.0.0" = {
      name = "pug-walk";
      packageName = "pug-walk";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-walk/-/pug-walk-2.0.0.tgz";
        sha512 = "yYELe9Q5q9IQhuvqsZNwA5hfPkMJ8u92bQLIMcsMxf/VADjNtEYptU+inlufAFYcWdHlwNfZOEnOOQrZrcyJCQ==";
      };
    };
    "request-light-0.5.8" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.5.8.tgz";
        sha512 = "3Zjgh+8b5fhRJBQZoy+zbVKpAQGLyka0MPgW3zruTF4dFFJ8Fqcfu9YsAvi/rvdcaTeWG3MkbZv4WKxAn/84Lg==";
      };
    };
    "resolve-1.22.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.0.tgz";
        sha512 = "Hhtrw0nLeSrFQ7phPp4OOcVjLPIeMnRlr5mcnVuMe7M/7eBn98A3hmFRLoFo3DLZkivSYwhRUJTyPyWAk56WLw==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha1 = "dc5e698cbd079265bc73e0377681a4e4e83f616e";
      };
    };
    "token-stream-1.0.0" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz";
        sha1 = "cc200eab2613f4166d27ff9afc7ca56d49df6eb4";
      };
    };
    "too-wordy-0.3.4" = {
      name = "too-wordy";
      packageName = "too-wordy";
      version = "0.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/too-wordy/-/too-wordy-0.3.4.tgz";
        sha512 = "EU+UA4zHc06TkVQaravNNVdqX763/ENTIOKiKlqSJ6WKCPwLxHjvY3d0uEJYaq92iojyHPwD2iaYbZKjdw3icA==";
      };
    };
    "uc.micro-1.0.6" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.6.tgz";
        sha512 = "8Y75pvTYkLJW2hWQHXxoqRgV7qb9B+9vFEtidML+7koHUFapnVJAZ6cKs+Qjz5Aw3aZWHMC6u0wJE3At+nSGwA==";
      };
    };
    "upath-2.0.1" = {
      name = "upath";
      packageName = "upath";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/upath/-/upath-2.0.1.tgz";
        sha512 = "1uEe95xksV1O0CYKXo8vQvN1JEbtJp7lb7C5U9HMsIp6IVwntkH/oNUzyVNQSd4S1sYk2FpSSW44FqMc8qee5w==";
      };
    };
    "void-elements-3.1.0" = {
      name = "void-elements";
      packageName = "void-elements";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/void-elements/-/void-elements-3.1.0.tgz";
        sha1 = "614f7fbf8d801f0bb5f0661f5b2f5785750e4f09";
      };
    };
    "vscode-css-languageservice-6.0.1" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.0.1.tgz";
        sha512 = "81n/eeYuJwQdvpoy6IK1258PtPbO720fl13FcJ5YQECPyHMFkmld1qKHwPJkyLbLPfboqJPM53ys4xW8v+iBVw==";
      };
    };
    "vscode-html-languageservice-5.0.0" = {
      name = "vscode-html-languageservice";
      packageName = "vscode-html-languageservice";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.0.0.tgz";
        sha512 = "KJG13z54aLszskp3ETf8b1EKDypr2Sf5RUsfR6OXmKqEl2ZUfyIxsWz4gbJWjPzoJZx/bGH0ZXVwxJ1rg8OKRQ==";
      };
    };
    "vscode-json-languageservice-5.0.0" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-5.0.0.tgz";
        sha512 = "1/+1TJBRFrfCNizmrW0fbIvguKzzO+4ehlqWCCnF7ioSACUGHrYop4ANb+eRnFaCP6fi3+i+llJC5Y5yAvmL6w==";
      };
    };
    "vscode-jsonrpc-8.0.1" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.0.1.tgz";
        sha512 = "N/WKvghIajmEvXpatSzvTvOIz61ZSmOSa4BRA4pTLi+1+jozquQKP/MkaylP9iB68k73Oua1feLQvH3xQuigiQ==";
      };
    };
    "vscode-languageserver-8.0.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.0.1.tgz";
        sha512 = "sn7SjBwWm3OlmLtgg7jbM0wBULppyL60rj8K5HF0ny/MzN+GzPBX1kCvYdybhl7UW63V5V5tRVnyB8iwC73lSQ==";
      };
    };
    "vscode-languageserver-protocol-3.17.1" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.1.tgz";
        sha512 = "BNlAYgQoYwlSgDLJhSG+DeA8G1JyECqRzM2YO6tMmMji3Ad9Mw6AW7vnZMti90qlAKb0LqAlJfSVGEdqMMNzKg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.5" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.5.tgz";
        sha512 = "1ah7zyQjKBudnMiHbZmxz5bYNM9KKZYz+5VQLj+yr8l+9w3g+WAhCkUkWbhMEdC5u0ub4Ndiye/fDyS8ghIKQg==";
      };
    };
    "vscode-languageserver-types-3.17.1" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.1.tgz";
        sha512 = "K3HqVRPElLZVVPtMeKlsyL9aK0GxGQpvtAUTfX4k7+iJ4mc1M+JM+zQwkgGy2LzY0f0IAafe8MKqIkJrxfGGjQ==";
      };
    };
    "vscode-nls-5.0.1" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.0.1.tgz";
        sha512 = "hHQV6iig+M21lTdItKPkJAaWrxALQb/nqpVffakO4knJOh3DrU2SXOMzUzNgo1eADPzu3qSsJY1weCzvR52q9A==";
      };
    };
    "vscode-uri-2.1.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.1.2.tgz";
        sha512 = "8TEXQxlldWAuIODdukIb+TR5s+9Ds40eSJrw+1iDDA9IFORPjMELarNQE3myz5XIkWWpdprmJjm1/SxMlWOC8A==";
      };
    };
    "vscode-uri-3.0.3" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.3.tgz";
        sha512 = "EcswR2S8bpR7fD0YPeS7r2xXExrScVMxg4MedACaWHEtx9ftCF/qHG1xGkolzTPcEmjTavCQgbVzHUIdTMzFGA==";
      };
    };
    "weasel-words-0.1.1" = {
      name = "weasel-words";
      packageName = "weasel-words";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/weasel-words/-/weasel-words-0.1.1.tgz";
        sha1 = "7137946585c73fe44882013853bd000c5d687a4e";
      };
    };
    "with-7.0.2" = {
      name = "with";
      packageName = "with";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/with/-/with-7.0.2.tgz";
        sha512 = "RNGKj82nUPg3g5ygxkQl0R937xLyho1J24ItRCBTr/m1YnZkzJy1hUiHUJrc/VlsDQzsCnInEGSg3bci0Lmd4w==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  lua-fmt = nodeEnv.buildNodePackage {
    name = "lua-fmt";
    packageName = "lua-fmt";
    version = "2.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/lua-fmt/-/lua-fmt-2.6.0.tgz";
      sha512 = "J4D7TK+BhSJ9ePQPpZPlu/aHE3X9ojN+D7DNv1HXZPryBJ74XWVmXpRX+qceXdE15TUsQRCj9w81waVOOFhfWA==";
    };
    dependencies = [
      sources."@types/commander-2.12.2"
      sources."@types/diff-3.5.5"
      sources."@types/get-stdin-5.0.1"
      sources."@types/node-17.0.36"
      sources."commander-2.20.3"
      sources."diff-3.5.0"
      sources."get-stdin-5.0.1"
      sources."luaparse-git+https://github.com/oxyc/luaparse#ac42a00ebf4020b8c9d3219e4b0f84bf7ce6e802"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Format Lua code";
      homepage = "https://github.com/trixnz/lua-fmt";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  write-good = nodeEnv.buildNodePackage {
    name = "write-good";
    packageName = "write-good";
    version = "1.0.8";
    src = fetchurl {
      url = "https://registry.npmjs.org/write-good/-/write-good-1.0.8.tgz";
      sha512 = "P1Ct7+DNrOcr2JAxDZ3Q5i5sx2LSveu7iLaoUL0A+YiG0GKf0l5+9j3rwMeyh6JeTL1+HfQV1rnwEvzhNIvpFw==";
    };
    dependencies = [
      sources."adverb-where-0.2.5"
      sources."commander-2.20.3"
      sources."e-prime-0.10.4"
      sources."no-cliches-0.3.4"
      sources."passive-voice-0.1.0"
      sources."too-wordy-0.3.4"
      sources."weasel-words-0.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Naive linter for English prose";
      homepage = "https://github.com/btford/write-good#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@fsouza/prettierd" = nodeEnv.buildNodePackage {
    name = "_at_fsouza_slash_prettierd";
    packageName = "@fsouza/prettierd";
    version = "0.21.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@fsouza/prettierd/-/prettierd-0.21.1.tgz";
      sha512 = "xLGvk2csfCqTT3MZfXC7uGxdAy0HkMiYoVz2vCQbxNHCLSLBEoejNcbNh+MPWulRPSVBYN8jJJge6yychCU5KA==";
    };
    dependencies = [
      sources."core_d-5.0.1"
      sources."has-flag-4.0.0"
      sources."nanolru-1.0.0"
      sources."prettier-2.6.2"
      sources."supports-color-8.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "prettier, as a daemon";
      homepage = "https://github.com/fsouza/prettierd";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  nginxbeautifier = nodeEnv.buildNodePackage {
    name = "nginxbeautifier";
    packageName = "nginxbeautifier";
    version = "1.0.19";
    src = fetchurl {
      url = "https://registry.npmjs.org/nginxbeautifier/-/nginxbeautifier-1.0.19.tgz";
      sha512 = "Gmx8qZbJtemVvHOQEQMu2GrNLwODzs//lWe3h6kFDJpCviObjj3+A4bb21wEhtIrIH4/ZWUCqpkfemEBIMlSvQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Nginx Configuration Beautifier";
      homepage = "https://github.com/vasilevich/nginxbeautifier#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  rustywind = nodeEnv.buildNodePackage {
    name = "rustywind";
    packageName = "rustywind";
    version = "0.15.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/rustywind/-/rustywind-0.15.0.tgz";
      sha512 = "vj7MQ3Jdf2GLap8MYr0Ui04f8bBQksYGTLwkrVsIaZ+uJbDuiyPCAMYlTJEeruAolD+fJj35NxTSSHA4GgOGhQ==";
    };
    dependencies = [
      sources."agent-base-5.1.1"
      sources."debug-4.3.4"
      sources."https-proxy-agent-4.0.0"
      sources."ms-2.1.2"
      sources."proxy-from-env-1.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CLI for organizing Tailwind CSS classes";
      homepage = "https://github.com/avencera/rustywind#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  markdownlint = nodeEnv.buildNodePackage {
    name = "markdownlint";
    packageName = "markdownlint";
    version = "0.25.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/markdownlint/-/markdownlint-0.25.1.tgz";
      sha512 = "AG7UkLzNa1fxiOv5B+owPsPhtM4D6DoODhsJgiaNg1xowXovrYgOnLqAgOOFQpWOlHFVQUzjMY5ypNNTeov92g==";
    };
    dependencies = [
      sources."argparse-2.0.1"
      sources."entities-2.1.0"
      sources."linkify-it-3.0.3"
      sources."markdown-it-12.3.2"
      sources."mdurl-1.0.1"
      sources."uc.micro-1.0.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Node.js style checker and lint tool for Markdown/CommonMark files.";
      homepage = "https://github.com/DavidAnson/markdownlint";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@volar/vue-language-server" = nodeEnv.buildNodePackage {
    name = "_at_volar_slash_vue-language-server";
    packageName = "@volar/vue-language-server";
    version = "0.35.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@volar/vue-language-server/-/vue-language-server-0.35.2.tgz";
      sha512 = "V1AfLK/paicjkp6gm4TJSsdidzPEN/7XXvKF5axAyC6X6srbAm0PkBJtAa2d8PMqXRbk4C8wUr9ggAuxQoBlfw==";
    };
    dependencies = [
      sources."@babel/helper-validator-identifier-7.16.7"
      sources."@babel/parser-7.18.4"
      sources."@babel/types-7.18.4"
      sources."@emmetio/abbreviation-2.2.3"
      sources."@emmetio/css-abbreviation-2.1.4"
      sources."@emmetio/scanner-1.0.0"
      sources."@johnsoncodehk/html2pug-1.0.0"
      sources."@johnsoncodehk/pug-beautify-0.2.2"
      sources."@volar/code-gen-0.35.2"
      sources."@volar/pug-language-service-0.35.2"
      sources."@volar/shared-0.35.2"
      sources."@volar/source-map-0.35.2"
      sources."@volar/transforms-0.35.2"
      sources."@volar/typescript-language-service-0.35.2"
      sources."@volar/vue-code-gen-0.35.2"
      sources."@volar/vue-language-service-0.35.2"
      sources."@volar/vue-language-service-types-0.35.2"
      sources."@volar/vue-typescript-0.35.2"
      (sources."@vscode/emmet-helper-2.8.4" // {
        dependencies = [
          sources."vscode-uri-2.1.2"
        ];
      })
      sources."@vue/compiler-core-3.2.36"
      sources."@vue/compiler-dom-3.2.36"
      sources."@vue/compiler-sfc-3.2.36"
      sources."@vue/compiler-ssr-3.2.36"
      sources."@vue/reactivity-3.2.36"
      sources."@vue/reactivity-transform-3.2.36"
      sources."@vue/shared-3.2.36"
      sources."acorn-7.4.1"
      sources."asap-2.0.6"
      sources."assert-never-1.2.1"
      sources."babel-walk-3.0.0-canary-5"
      sources."call-bind-1.0.2"
      sources."character-parser-2.2.0"
      sources."constantinople-4.0.1"
      sources."doctypes-1.1.0"
      (sources."dom-serializer-1.4.1" // {
        dependencies = [
          sources."entities-2.2.0"
        ];
      })
      sources."domelementtype-2.3.0"
      sources."domhandler-4.3.1"
      sources."domutils-2.8.0"
      sources."emmet-2.3.6"
      sources."entities-3.0.1"
      sources."estree-walker-2.0.2"
      sources."function-bind-1.1.1"
      sources."get-intrinsic-1.1.1"
      sources."has-1.0.3"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.0"
      sources."htmlparser2-7.2.0"
      sources."is-core-module-2.9.0"
      sources."is-expression-4.0.0"
      sources."is-promise-2.2.2"
      sources."is-regex-1.1.4"
      sources."js-stringify-1.0.2"
      sources."jsonc-parser-2.3.1"
      sources."jstransformer-1.0.0"
      sources."lru-cache-6.0.0"
      sources."magic-string-0.25.9"
      sources."nanoid-3.3.4"
      sources."object-assign-4.1.1"
      sources."path-parse-1.0.7"
      sources."picocolors-1.0.0"
      sources."postcss-8.4.14"
      sources."promise-7.3.1"
      sources."pug-3.0.2"
      sources."pug-attrs-3.0.0"
      sources."pug-code-gen-3.0.2"
      sources."pug-error-2.0.0"
      sources."pug-filters-4.0.0"
      sources."pug-lexer-5.0.1"
      sources."pug-linker-4.0.0"
      sources."pug-load-3.0.0"
      sources."pug-parser-6.0.0"
      sources."pug-runtime-3.0.1"
      sources."pug-strip-comments-2.0.0"
      sources."pug-walk-2.0.0"
      sources."request-light-0.5.8"
      sources."resolve-1.22.0"
      sources."semver-7.3.7"
      sources."source-map-0.6.1"
      sources."source-map-js-1.0.2"
      sources."sourcemap-codec-1.4.8"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."to-fast-properties-2.0.0"
      sources."token-stream-1.0.0"
      sources."upath-2.0.1"
      sources."void-elements-3.1.0"
      sources."vscode-css-languageservice-6.0.1"
      sources."vscode-html-languageservice-5.0.0"
      (sources."vscode-json-languageservice-5.0.0" // {
        dependencies = [
          sources."jsonc-parser-3.0.0"
        ];
      })
      sources."vscode-jsonrpc-8.0.1"
      sources."vscode-languageserver-8.0.1"
      sources."vscode-languageserver-protocol-3.17.1"
      sources."vscode-languageserver-textdocument-1.0.5"
      sources."vscode-languageserver-types-3.17.1"
      sources."vscode-nls-5.0.1"
      sources."vscode-uri-3.0.3"
      sources."with-7.0.2"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://github.com/johnsoncodehk/volar#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
