# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@types/commander-2.12.2" = {
      name = "_at_types_slash_commander";
      packageName = "@types/commander";
      version = "2.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/commander/-/commander-2.12.2.tgz";
        sha512 = "0QEFiR8ljcHp9bAbWxecjVRuAMr16ivPiGOw6KFQBVrVd0RQIcM3xKdRisH2EDWgVWujiYtHwhSkSUoAAGzH7Q==";
      };
    };
    "@types/diff-3.5.3" = {
      name = "_at_types_slash_diff";
      packageName = "@types/diff";
      version = "3.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/diff/-/diff-3.5.3.tgz";
        sha512 = "YrLagYnL+tfrgM7bQ5yW34pi5cg9pmh5Gbq2Lmuuh+zh0ZjmK2fU3896PtlpJT3IDG2rdkoG30biHJepgIsMnw==";
      };
    };
    "@types/get-stdin-5.0.1" = {
      name = "_at_types_slash_get-stdin";
      packageName = "@types/get-stdin";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/get-stdin/-/get-stdin-5.0.1.tgz";
        sha1 = "46afbcaf09e94fe025afa07ae994ac3168adbdf3";
      };
    };
    "@types/node-15.6.1" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "15.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-15.6.1.tgz";
        sha512 = "7EIraBEyRHEe7CH+Fm1XvgqU6uwZN8Q7jppJGcqjROMT29qhAuuOxYB1uEY5UMYQKEmA5D+5tBnhdaPXSsLONA==";
      };
    };
    "adverb-where-0.2.5" = {
      name = "adverb-where";
      packageName = "adverb-where";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/adverb-where/-/adverb-where-0.2.5.tgz";
        sha512 = "JiQe2U1UR8l10jPrXv/PmlDhOLZpsxqjvTp+k6Dm5wYDUULdMZytDRmovkXU8X6V9o0sg0FBdetv3VXHAZZK5Q==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "diff-3.5.0" = {
      name = "diff";
      packageName = "diff";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-3.5.0.tgz";
        sha512 = "A46qtFgd+g7pDZinpnwiRJtxbC1hpgf0uzP3iG89scHk0AUC7A1TGxf5OiiOUv/JMZR8GOt8hL900hV0bOy5xA==";
      };
    };
    "e-prime-0.10.4" = {
      name = "e-prime";
      packageName = "e-prime";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/e-prime/-/e-prime-0.10.4.tgz";
        sha512 = "tzBmM2mFSnAq5BuxPSyin6qXb3yMe1wufJN7L7ZPcEWS5S+jI2dhKQEoqHVEcSMMXo/j5lcWpX5jzA6wLSmX6w==";
      };
    };
    "get-stdin-5.0.1" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-5.0.1.tgz";
        sha1 = "122e161591e21ff4c52530305693f20e6393a398";
      };
    };
    "luaparse-git://github.com/oxyc/luaparse#ac42a00ebf4020b8c9d3219e4b0f84bf7ce6e802" = {
      name = "luaparse";
      packageName = "luaparse";
      version = "0.2.1";
      src = fetchgit {
        url = "git://github.com/oxyc/luaparse";
        rev = "ac42a00ebf4020b8c9d3219e4b0f84bf7ce6e802";
        sha256 = "f813d671f8f8088d70d29f7a7770bdd5ed41ed97240ae9346d7ced0c094ee049";
      };
    };
    "no-cliches-0.3.4" = {
      name = "no-cliches";
      packageName = "no-cliches";
      version = "0.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-cliches/-/no-cliches-0.3.4.tgz";
        sha512 = "oUqnng1vhKLaA4GR+OzVbLuZZ7OOguKCtMHxHMiyP8+9mXidKfoCyc030LbAyNI3xcgCHHyitK3Q8wP+w6DwVQ==";
      };
    };
    "passive-voice-0.1.0" = {
      name = "passive-voice";
      packageName = "passive-voice";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/passive-voice/-/passive-voice-0.1.0.tgz";
        sha1 = "16ff91ae40ba0e92c43e671763fdc842a70270b1";
      };
    };
    "too-wordy-0.3.4" = {
      name = "too-wordy";
      packageName = "too-wordy";
      version = "0.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/too-wordy/-/too-wordy-0.3.4.tgz";
        sha512 = "EU+UA4zHc06TkVQaravNNVdqX763/ENTIOKiKlqSJ6WKCPwLxHjvY3d0uEJYaq92iojyHPwD2iaYbZKjdw3icA==";
      };
    };
    "weasel-words-0.1.1" = {
      name = "weasel-words";
      packageName = "weasel-words";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/weasel-words/-/weasel-words-0.1.1.tgz";
        sha1 = "7137946585c73fe44882013853bd000c5d687a4e";
      };
    };
  };
in
{
  lua-fmt = nodeEnv.buildNodePackage {
    name = "lua-fmt";
    packageName = "lua-fmt";
    version = "2.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/lua-fmt/-/lua-fmt-2.6.0.tgz";
      sha1 = "ef9ac0573d1da7330dca09c022c39a33aed347a3";
    };
    dependencies = [
      sources."@types/commander-2.12.2"
      sources."@types/diff-3.5.3"
      sources."@types/get-stdin-5.0.1"
      sources."@types/node-15.6.1"
      sources."commander-2.20.3"
      sources."diff-3.5.0"
      sources."get-stdin-5.0.1"
      sources."luaparse-git://github.com/oxyc/luaparse#ac42a00ebf4020b8c9d3219e4b0f84bf7ce6e802"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Format Lua code";
      homepage = "https://github.com/trixnz/lua-fmt";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  write-good = nodeEnv.buildNodePackage {
    name = "write-good";
    packageName = "write-good";
    version = "1.0.8";
    src = fetchurl {
      url = "https://registry.npmjs.org/write-good/-/write-good-1.0.8.tgz";
      sha512 = "P1Ct7+DNrOcr2JAxDZ3Q5i5sx2LSveu7iLaoUL0A+YiG0GKf0l5+9j3rwMeyh6JeTL1+HfQV1rnwEvzhNIvpFw==";
    };
    dependencies = [
      sources."adverb-where-0.2.5"
      sources."commander-2.20.3"
      sources."e-prime-0.10.4"
      sources."no-cliches-0.3.4"
      sources."passive-voice-0.1.0"
      sources."too-wordy-0.3.4"
      sources."weasel-words-0.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Naive linter for English prose";
      homepage = "https://github.com/btford/write-good#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
