scan_timeout = 10
add_newline = false

format = """\
$shlvl\
$directory\
$status \
$fill \
\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$helm\
$lua\
$python\
$rust\
$terraform\
$nix_shell\
$aws\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$time\
$container
$shell\
$character"""

[aws]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[git_branch]
truncation_length = 12

[git_status]
disabled = true

[python]
version_format = "v${major}.${minor}"
format = '\([${symbol}(${version})]($style)\)'
