export PYTHONSTARTUP=$HOME/.pythonstartup

source ~/.config/zsh/settings.zsh
source ~/.config/zsh/ssh.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/fzf.zsh
source ~/work/credentials

bindkey '^ ' autosuggest-accept
bindkey '^p' backward-word
bindkey '^n' forward-word

export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$HOME/.zplug/mfaerevaag/wd/bin:$PATH"

. /usr/local/opt/asdf/asdf.sh
. /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash

localdocker() {
    unset DOCKER_HOST
    unset DOCKER_TLS_VERIFY
    unset PYTEST_MOCK_RESOURCES_HOST
}

remotedocker() {
  export DOCKER_HOST=tcp://desktop:2376
  export DOCKER_TLS_VERIFY=1
  export PYTEST_MOCK_RESOURCES_HOST=desktop
}

autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
  compinit
else
  compinit -C
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export WORMHOLE_RELAY_URL=ws://wormhole.schireson.com:4000/v1
export WORMHOLE_TRANSIT_HELPER=tcp:wormhole.schireson.com:4001

export PATH="/usr/local/opt/terraform@0.11/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export DOCKER_BUILDKIT=1

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
wd() {
  . /Users/dancardin/bin/wd/wd.sh
}
