# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=/Users/dan/.zgen/robbyrussell/oh-my-zsh-master

# ### General modules
source "/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found/command-not-found.plugin.zsh"
source "/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/extract/extract.plugin.zsh"
source "/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/pip/pip.plugin.zsh"
source "/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/python/python.plugin.zsh"
source "/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/ssh-agent/ssh-agent.plugin.zsh"
source "/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo/sudo.plugin.zsh"
source "/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/virtualenv/virtualenv.plugin.zsh"
source "/Users/dan/.zgen/DanCardin/zsh-vim-mode-master/zsh-vim-mode.plugin.zsh"
source "/Users/dan/.zgen/RobSis/zsh-completion-generator-master/zsh-completion-generator.plugin.zsh"
source "/Users/dan/.zgen/chrissicool/zsh-256color-master/zsh-256color.plugin.zsh"
source "/Users/dan/.zgen/djui/alias-tips-master/alias-tips.plugin.zsh"
source "/Users/dan/.zgen/mafredri/zsh-async-master/async.plugin.zsh"
source "/Users/dan/.zgen/unixorn/autoupdate-zgen-master/autoupdate-zgen.plugin.zsh"
source "/Users/dan/.zgen/zsh-users/zsh-autosuggestions-master/zsh-autosuggestions.plugin.zsh"
source "/Users/dan/.zgen/zsh-users/zsh-completions-master/zsh-completions.plugin.zsh"
source "/Users/dan/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.plugin.zsh"
source "/Users/dan/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/Users/dan/.zgen/sindresorhus/pure-master/pure.plugin.zsh"

# ### Plugins & Completions
fpath=(/Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found /Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/extract /Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/pip /Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/python /Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/ssh-agent /Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo /Users/dan/.zgen/robbyrussell/oh-my-zsh-master/plugins/virtualenv /Users/dan/.zgen/DanCardin/zsh-vim-mode-master /Users/dan/.zgen/RobSis/zsh-completion-generator-master /Users/dan/.zgen/chrissicool/zsh-256color-master /Users/dan/.zgen/djui/alias-tips-master /Users/dan/.zgen/mafredri/zsh-async-master /Users/dan/.zgen/unixorn/autoupdate-zgen-master /Users/dan/.zgen/zsh-users/zsh-autosuggestions-master /Users/dan/.zgen/zsh-users/zsh-completions-master /Users/dan/.zgen/zsh-users/zsh-history-substring-search-master /Users/dan/.zgen/zsh-users/zsh-syntax-highlighting-master /Users/dan/.zgen/sindresorhus/pure-master ${fpath})

autoload -Uz compinit && \
   compinit -C 

# ### Recompilation triggers
read -rd '' ages <<AGES; read -rd '' shas <<SHAS
1507591457
AGES
2f9d413a35f355d9b6e0359167000071dc32fb55fff124dc429714780d9f93a2  /Users/dan/.zshrc
SHAS
if [[ -n "$ZGEN_RESET_ON_CHANGE" \
   && "$(stat -Lc "%Y" 2>/dev/null $ZGEN_RESET_ON_CHANGE || \
         stat -Lf "%m"             $ZGEN_RESET_ON_CHANGE)" != "$ages" \
   && "$(shasum -a 256             $ZGEN_RESET_ON_CHANGE)" != "$shas" ]]; then
   printf %s\\n '-- zgen: Files in $ZGEN_RESET_ON_CHANGE changed; resetting `init.zsh`...'
   zgen reset
fi

# }}}
