#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save

ZSH=/Users/dcardin/.zgen/sorin-ionescu/prezto-master

# init prezto
zstyle ':prezto:module:prompt' 'theme' 'sorin'

#
source "/Users/dcardin/.zgen/sorin-ionescu/prezto-master/init.zsh"
source "/Users/dcardin/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/Users/dcardin/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.plugin.zsh"
source "/Users/dcardin/.zgen/djui/alias-tips-master/alias-tips.plugin.zsh"
source "/Users/dcardin/.zgen/sharat87/zsh-vim-mode-master/zsh-vim-mode.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/Users/dcardin/.zgen/sorin-ionescu/prezto-master /Users/dcardin/.zgen/zsh-users/zsh-syntax-highlighting-master /Users/dcardin/.zgen/zsh-users/zsh-history-substring-search-master /Users/dcardin/.zgen/djui/alias-tips-master /Users/dcardin/.zgen/sharat87/zsh-vim-mode-master /Users/dcardin/.zgen/zsh-users/zsh-completions-master/src ${fpath})

# init prezto
pmodload 'environment' 'terminal' 'editor' 'history' 'directory' 'spectrum' 'utility' 'completion' 'prompt' 'git' 'syntax-highlighting' 'completion' 'command-not-found' 'osx' 'python' 'ssh' 'tmux' 
